# POC1
# Here we created the kubernetes basic pod with postgres container
# To access the pod directly from host system or another system you need to forward the pod port to host port
# kubectl port-forward pd-pod-name 8888:5432 ie HOSTPOST:POD_CONTAINER_PORT
# Equivalent Docker command : docker container run -itd -p 8888:5432--name db-pod-con-name -e POSTGRES_DB=postgresdb -e POSTGRES_USER=admin -e POSTGRES_PASSWORD=password postgres:12





apiVersion: v1
kind: Pod
metadata:
  name: pd-pod-name # POD NAME
  labels:
    app: pd-label  # POD LABEL FROM WHICH POD WILL BE RECOGNISED OR SELECTED BY OTHER SERVICES
spec:
  volumes:
    - name: config-volume
      configMap:
        name: postgres-config
  containers:
    - name: db-pod-con-name # CONTAINER NAME
      image: 'postgres:12'
      env:  # ENVIRONMENTAL VARIABLES
        - name: POSTGRES_DB
          value: postgresdb
        - name: POSTGRES_USER
          value: admin
        - name: 
          value: password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata

      # command: [ "/bin/sh", "-c", "ls /etc/config/" ]
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config